build:
  image: python:2.7
  commands:
    - cd django-verdant

    # Install requirements
    - apt-get update -y && apt-get install python-dev libldap2-dev libsasl2-dev
    - XDG_CACHE_HOME=/drone/pip-cache pip install wheel
    - XDG_CACHE_HOME=/drone/pip-cache pip install -r requirements.txt

    # Run system checks
    - python manage.py check

    # Check for missing migrations
    - bash -c "! python manage.py makemigrations -e --dry-run --noinput"

cache:
  mount:
    - /drone/pip-cache
