---
- hosts: production
  user: ${user} 
  vars: 
    node_version: "0.10.12"
    node_prefix: "node-v${node_version}"
    node_tarball: "${node_prefix}.tar.gz"
    node_path: "/usr/local" 
  vars_files:
    - vars.yml

  gather_facts: false
  sudo: false

  tasks:
  
  - name: Create the djangoapps group
    group: name=djangoapps state=present
  
  - name: Create user
    user: name=${project_name} group=djangoapps shell="/bin/bash" state=present

  - name: Create the django directory
    file: state=directory path=${django_root} mode=2775 owner=root group=djangoapps
  - name: Create user
    user: name=${project_name} group=djangoapps shell="/bin/bash" state=present

  - name: Generate SSH keys for the deployment user
    user: name=${project_name} generate_ssh_key=yes ssh_key_bits=2048

  - name: Show SSH public key
    command: /bin/cat /home/${project_name}/.ssh/id_rsa.pub

  - name: Install the required system packages
    apt: pkg=${item} state=installed update-cache=yes
    with_items: ${system_packages}

  - name: Install global python packages
    pip: name=${item} state=present use_mirrors=no
    with_items: ${python_packages}

  - include: nodejs.yml


 
  - name: Copy the nginx vhost 
    template: src=files/templates/nginx-vhost.conf.j2 dest=/etc/nginx/sites-enabled/${project_name}.conf
    notify:
    - restart nginx

  - name: Copy my public key for SSH as the deployment user
    authorized_key: user=${project_name} key="{{ lookup('file', '/home/stewart/.ssh/id_rsa.pub') }}" manage_dir=no

